{% set name = "fairseq" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 61206358b79f325ea0b46cfd8c95cdb81bfbcfb43cf12b47d1d5124ce7321d3b

build:
  number: 1
  entry_points:
    - fairseq-eval-lm = fairseq_cli.eval_lm:cli_main
    - fairseq-generate = fairseq_cli.generate:cli_main
    - fairseq-interactive = fairseq_cli.interactive:cli_main
    - fairseq-preprocess = fairseq_cli.preprocess:cli_main
    - fairseq-score = fairseq_cli.score:main
    - fairseq-train = fairseq_cli.train:cli_main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pytorch
    - cython
    - setuptools
    - pycparser
    - python_abi ==3.6
  run:
    - python
    - cffi
    - numpy
    - regex
    - sacrebleu
    - pycparser
    - cython
    - pytorch
    - tqdm

test:
  imports:
    - examples
    - examples.noisychannel
  commands:
    - fairseq-eval-lm --help
    - fairseq-generate --help
    - fairseq-interactive --help
    - fairseq-preprocess --help
    - fairseq-score --help
    - fairseq-train --help

about:
  home: https://pypi.org/project/fairseq/
  summary: Facebook AI Research Sequence-to-Sequence Toolkit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar


{"python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|3.4.*|>=3.5,<3.6.0a0']",
 'libcxx', "libcxx[version='>=10.0.0|>=10.0.1|>=9.0.1|>=9.0.0|>=4.0.1']",
 "readline[version='6.2.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0|7.0.*|7.*']",
 "python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|3.4.*']",
 "readline[version='6.2.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0|7.*|7.0.*']",
 "python[version='3.7.*|3.8.*']",
 "libcxx[version='>=10.0.0|>=10.0.1|>=9.0.1|>=9.0.0']",
 "libcxx[version='>=4.0.1']",
 "libcxxabi[version='4.0.1|4.0.1|8.0.0|8.0.0|8.0.0|8.0.0|8.0.1',build='hebd6815_0|1|2|3|0|4|hcfea43d_1']",
 'setuptools', "python[version='2.7.*|3.5.*|3.6.*|3.6.9|>=3.5,<3.6.0a0|3.4.*',build='1_73_pypy|2_73_pypy|0_73_pypy']",
 "python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0|3.4.*']",
 "gdbm[version='>=1.18,<1.19.0a0']",
 "python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']",
 'pycparser'}

